### ISSUE TITLE
Make C-lightning capable of using bitcoind directly, without proxy

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/c-lightning-wrapper#17]
This is so bitcoind will be enforced as a dependency of c-lightning only if bitcoind is in full archival mode

**Comment by chrisguida** [comment]
@dr-bonez @ProofOfKeags is this still needed?

**Comment by dr-bonez** [comment]
Should we done with a config pointer rather than a health check

**Comment by chrisguida** [comment]
Keeping proxy required for now, doesn't hurt anything regardless of whether bitcoind is archival. Renaming and downgrading to P2.
