### ISSUE TITLE
Disable rest api docs interface

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/c-lightning-wrapper#28]
This is technically a browser interface but isn't the "main" interface for c-lightning. But it shows up in the UI as a button.

Perhaps we should just disable?

**Comment by ProofOfKeags** [comment]
Yeah, disabling it seems appropriate in this case.

**Comment by chrisguida** [comment]
Fixed by 43ca8c4d59f502114f700a7843b94b1756176eaf
