### ISSUE TITLE
[bug]: investigate why c-lightning-http-plugin sometimes eats up CPU

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/c-lightning-wrapper#29]
<img width="1031" alt="Screen Shot 2022-01-26 at 3 52 43 PM" src="https://user-images.githubusercontent.com/7445670/151253281-ad8b41da-d84d-4cbb-a209-a5e63e4af440.png">

**Comment by ProofOfKeags** [comment]
Does this occur even after sync? It is sensible for c-lightning to have serious CPU spikes during block processing.

**Comment by chrisguida** [comment]
That might be it
