### ISSUE TITLE
[feat]: enhance CLBOSS experience

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/c-lightning-wrapper#50]
1. Either disable clboss by default, or present a prominent notice before install saying that any funds deposited to this CLN node will automatically be used by clboss to open channels
2. Add some extra config options for the main clboss preferences: --clboss-min-onchain=<satoshis>, --clboss-auto-close=<true|false>, --clboss-zerobasefee=<require|allow|disallow>, --clboss-min-channel=<satoshis> / --clboss-max-channel=<satoshis>
~~3. Add a page that shows the output of "clboss-status" command~~
~~4. Add an "action" for "clboss-unmanage" and similar commands like "clboss-ignore-onchain"~~
~~5. Update instructions with a CLBOSS section~~

Edit: 3, 4, and 5 moved, see [this comment](https://github.com/Start9Labs/c-lightning-wrapper/issues/50#issuecomment-1198168442)

**Comment by swissrouting** [comment]
About point 1, here's an example of the kind of warning notice that could be helpful: https://github.com/rootzoll/raspiblitz/pull/3210/files#diff-163e46a15646dec737558922ccfff387750f8a1a789e5ae2d4404fb0b24b051bR27-R39

**Comment by chrisguida** [comment]
Fixed by #54.

Splitting out points 3, 4, and 5 into their own issues and adding to next release:

- [ ] https://github.com/Start9Labs/c-lightning-wrapper/issues/56
- [ ] https://github.com/Start9Labs/c-lightning-wrapper/issues/57
- [ ] https://github.com/Start9Labs/c-lightning-wrapper/issues/58
